/*
 * Zeo Project Template HTML defaults
 * Provides styled fallback pages when a template does not supply an info.html.
 */

#ifndef ZEO_TEMPLATE_DEFAULT_HTML_H
#define ZEO_TEMPLATE_DEFAULT_HTML_H

#include <wx/string.h>

// Uses _() translation macro which is defined globally.

// Welcome (no template selected) page.
inline wxString GetWelcomeHtml()
{
    return wxString(
        "<!DOCTYPE html>"
        "<html lang=\"en\">"
        "<head>"
        "<meta charset=\"UTF-8\">"
        "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">"
        "<title>Zeo Project Template Selector</title>"
        "<style>"
        "body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif; margin: 0; padding: 24px; background: #1a1a1a; color: #ffffff; min-height: 100vh; box-sizing: border-box; }"
        ".container { max-width: 800px; margin: 0 auto; }"
        ".header { text-align: center; margin-bottom: 40px; }"
        ".logo { font-size: 2.5rem; font-weight: 600; color: #ffffff; margin-bottom: 8px; letter-spacing: -0.02em; }"
        ".subtitle { font-size: 1.1rem; color: #888888; }"
        ".welcome-card { background: #2a2a2a; border: 1px solid #333333; padding: 28px; border-radius: 12px; margin-bottom: 32px; }"
        ".welcome-card h2 { margin-top: 0; font-size: 1.5rem; font-weight: 500; margin-bottom: 12px; color: #ffffff; }"
        ".welcome-card p { color: #aaaaaa; line-height: 1.6; margin: 0; }"
        ".instructions { display: grid; grid-template-columns: repeat(auto-fit, minmax(280px, 1fr)); gap: 16px; margin-bottom: 32px; }"
        ".instruction-card { background: #222222; border: 1px solid #333333; border-radius: 8px; padding: 20px; transition: border-color 0.2s ease; }"
        ".instruction-card:hover { border-color: #555555; }"
        ".instruction-card h3 { color: #ffffff; margin-top: 0; margin-bottom: 8px; font-size: 1.1rem; font-weight: 500; }"
        ".instruction-card p { color: #999999; line-height: 1.5; margin: 0; font-size: 0.95rem; }"
        ".features { background: #222222; border: 1px solid #333333; border-radius: 8px; padding: 24px; margin-bottom: 24px; }"
        ".features h3 { color: #ffffff; margin-top: 0; margin-bottom: 16px; font-size: 1.2rem; font-weight: 500; }"
        ".features ul { color: #aaaaaa; line-height: 1.8; margin: 0; padding-left: 20px; }"
        ".features li { margin-bottom: 6px; }"
        ".features strong { color: #ffffff; font-weight: 500; }"
        ".tips { background: #2a2a2a; border: 1px solid #444444; border-radius: 8px; padding: 24px; }"
        ".tips h3 { color: #ffffff; margin-top: 0; margin-bottom: 16px; font-size: 1.2rem; font-weight: 500; }"
        ".tips p { color: #999999; line-height: 1.6; margin: 0 0 12px 0; font-size: 0.95rem; }"
        ".tips p:last-child { margin-bottom: 0; }"
        ".tips strong { color: #cccccc; }"
        ".highlight { background: #333333; padding: 2px 8px; border-radius: 4px; color: #ffffff; font-weight: 500; }"
        "</style>"
        "</head>"
        "<body>"
        "<div class=\"container\">"
        "<div class=\"header\">"
        "<div class=\"logo\">Zeo</div>"
        "<div class=\"subtitle\">" + _( "Project Template Selector" ) + "</div>"
        "</div>"
        "<div class=\"welcome-card\">"
        "<h2>" + _( "Welcome to Template Selection" ) + "</h2>"
        "<p>" + _( "Choose from pre-configured project templates to jumpstart your PCB design. Templates provide ready-to-use project structures with common components, libraries, and design rules." ) + "</p>"
        "</div>"
        "<div class=\"instructions\">"
        "<div class=\"instruction-card\">"
        "<h3>" + _( "Browse Templates" ) + "</h3>"
        "<p>" + _( "Navigate through the template tabs above to explore different categories. Each tab contains templates organized by type or complexity." ) + "</p>"
        "</div>"
        "<div class=\"instruction-card\">"
        "<h3>" + _( "Select a Template" ) + "</h3>"
        "<p>" + _( "Click on any template to " ) + "<span class=\"highlight\">" + _( "preview its details" ) + "</span>" + _(". The template information will appear here, showing descriptions and project structure." ) + "</p>"
        "</div>"
        "<div class=\"instruction-card\">"
        "<h3>" + _( "Customize Path" ) + "</h3>"
        "<p>" + _( "Use the " ) + "<span class=\"highlight\">" + _( "folder path" ) + "</span> " + _( "above to browse custom template directories. Click the folder icon to browse, or refresh to reload." ) + "</p>"
        "</div>"
        "<div class=\"instruction-card\">"
        "<h3>" + _( "Create Project" ) + "</h3>"
        "<p>" + _( "Once you've found the right template, click " ) + "<span class=\"highlight\">" + _( "OK" ) + "</span> " + _( "to create a new project based on it." ) + "</p>"
        "</div>"
        "</div>"
        "<div class=\"features\">"
        "<h3>" + _( "What You Get with Templates" ) + "</h3>"
        "<ul>"
        "<li><strong>" + _( "Pre-configured libraries" ) + "</strong> " + _( "- Common components and footprints already linked" ) + "</li>"
        "<li><strong>" + _( "Design rules" ) + "</strong> " + _( "- Appropriate electrical and mechanical constraints" ) + "</li>"
        "<li><strong>" + _( "Layer stackups" ) + "</strong> " + _( "- Optimized for the intended application" ) + "</li>"
        "<li><strong>" + _( "Documentation" ) + "</strong> " + _( "- README files and design notes" ) + "</li>"
        "</ul>"
        "</div>"
        "<div class=\"tips\">"
        "<h3>" + _( "Tips" ) + "</h3>"
        "<p><strong>" + _( "Start Simple:" ) + "</strong> " + _( "Begin with basic templates and add more elements as you go." ) + "</p>"
        "<p><strong>" + _( "Customize Later:" ) + "</strong> " + _( "Templates are starting points - modify libraries, rules, and layouts after project creation." ) + "</p>"
        "<p><strong>" + _( "Save Your Own:" ) + "</strong> " + _( "Create custom templates from your preferred settings for future projects." ) + "</p>"
        "</div>"
        "</div>"
        "</body>"
        "</html>"
    );
}

// Fallback when a specific template has no meta/info.html.
inline wxString GetTemplateInfoHtml( const wxString& aTemplateName )
{
    return wxString(
        "<!DOCTYPE html>"
        "<html lang=\"en\">"
        "<head>"
        "<meta charset=\"UTF-8\">"
        "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">"
        "<title>" + aTemplateName + " - Zeo Template</title>"
        "<style>"
        "body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif; margin: 0; padding: 24px; background: #1a1a1a; color: #ffffff; min-height: 100vh; box-sizing: border-box; }"
        ".container { max-width: 700px; margin: 0 auto; }"
        ".header { display: flex; align-items: center; gap: 12px; margin-bottom: 24px; }"
        ".badge { background: #333333; color: #ffffff; padding: 4px 12px; border-radius: 4px; font-size: 0.75rem; letter-spacing: 0.05em; text-transform: uppercase; }"
        "h1 { font-size: 1.75rem; margin: 0; font-weight: 500; }"
        "p { line-height: 1.6; color: #aaaaaa; }"
        ".cta { background: #222222; border: 1px solid #333333; padding: 20px 24px; border-radius: 8px; margin: 28px 0 20px; }"
        ".cta strong { color: #ffffff; }"
        ".steps { display: grid; gap: 12px; margin-top: 16px; }"
        ".step { background: #2a2a2a; border: 1px solid #333333; padding: 16px; border-radius: 6px; }"
        ".step h3 { margin: 0 0 6px 0; font-size: 1rem; color: #ffffff; font-weight: 500; }"
        ".step p { margin: 0; font-size: 0.9rem; }"
        ".edit-hint { background: #2a2a2a; border: 1px solid #444444; padding: 16px 20px; border-radius: 8px; margin-top: 24px; }"
        ".edit-hint strong { color: #cccccc; }"
        ".edit-hint p { margin: 8px 0 0 0; font-size: 0.9rem; }"
        "code { background: #333333; padding: 2px 6px; border-radius: 4px; font-size: 0.85rem; color: #ffffff; }"
        "</style>"
        "</head><body><div class=\"container\">"
        "<div class=\"header\"><div class=\"badge\">" + _( "Template" ) + "</div><h1>" + aTemplateName + "</h1></div>"
        "<p>" + _( "This project template doesn't include an info page yet. You can still use it to create a new project." ) + "</p>"
        "<div class=\"cta\">"
        "<strong>" + _( "To use this template:" ) + "</strong>"
        "<div class=\"steps\">"
        "<div class=\"step\"><h3>1. " + _( "Create the project" ) + "</h3><p>" + _( "Click OK below. Zeo will create a new project folder populated with the contents of this template." ) + "</p></div>"
        "<div class=\"step\"><h3>2. " + _( "Open schematic and PCB" ) + "</h3><p>" + _( "Use the Project Manager tree or launch Schematic and PCB editors to begin designing." ) + "</p></div>"
        "<div class=\"step\"><h3>3. " + _( "Review libraries & settings" ) + "</h3><p>" + _( "Confirm symbol/footprint libraries, design rules, and board stackup match your needs." ) + "</p></div>"
        "</div>"
        "</div>"
        "<div class=\"edit-hint\">"
        "<strong>" + _( "Add an info page:" ) + "</strong>"
        "<p>" + _( "Create a file at" ) + " <code>meta/info.html</code> " + _( "inside this template's directory to provide documentation or guidance." ) + "</p>"
        "</div>"
        "</div></body></html>"
    );
}

// Page shown when a template directory has no templates.
inline wxString GetNoTemplatesHtml()
{
    return wxString(
        "<!DOCTYPE html>"
        "<html lang=\"en\">"
        "<head>"
        "<meta charset=\"UTF-8\">"
        "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">"
        "<title>No Templates - Zeo</title>"
        "<style>"
        "body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif; margin: 0; padding: 24px; background: #1a1a1a; color: #ffffff; min-height: 100vh; box-sizing: border-box; }"
        ".container { max-width: 560px; margin: 0 auto; }"
        ".content { text-align: center; padding-top: 40px; }"
        ".title { font-size: 1.5rem; font-weight: 500; color: #ffffff; margin-bottom: 12px; }"
        ".message { font-size: 1rem; color: #888888; line-height: 1.6; margin-bottom: 32px; }"
        ".suggestions { text-align: left; background: #222222; border: 1px solid #333333; border-radius: 8px; padding: 24px; margin-bottom: 24px; }"
        ".suggestions h3 { color: #ffffff; margin-top: 0; margin-bottom: 16px; font-size: 1.1rem; font-weight: 500; }"
        ".suggestions ul { color: #aaaaaa; margin: 0; padding-left: 20px; line-height: 1.8; }"
        ".suggestions li { margin-bottom: 6px; }"
        ".action-hint { background: #2a2a2a; border: 1px solid #444444; border-radius: 8px; padding: 16px 20px; }"
        ".action-hint strong { color: #cccccc; }"
        ".action-hint span { color: #999999; }"
        "</style>"
        "</head>"
        "<body>"
        "<div class=\"container\">"
        "<div class=\"content\">"
        "<div class=\"title\">" + _( "No Templates Found" ) + "</div>"
        "<div class=\"message\">"
        + _( "The selected templates directory does not contain any project templates." )
        + "</div>"
        "<div class=\"suggestions\">"
        "<h3>" + _( "What to do:" ) + "</h3>"
        "<ul>"
        "<li>" + _( "Browse to a different templates directory using the folder icon" ) + "</li>"
        "<li>" + _( "Click the refresh icon to reload the current directory" ) + "</li>"
        "<li>" + _( "Check that the directory path contains valid templates" ) + "</li>"
        "<li>" + _( "Use the default system templates by navigating to a system templates tab" ) + "</li>"
        "</ul>"
        "</div>"
        "<div class=\"action-hint\">"
        "<strong>" + _( "Tip:" ) + "</strong> <span>" + _( "Templates are organized in subdirectories. Each template needs a 'meta' folder with configuration files." )
        + "</span></div>"
        "</div>"
        "</div>"
        "</body>"
        "</html>"
    );
}

#endif // ZENER_TEMPLATE_DEFAULT_HTML_H
