/*
 * This program source code file is part of KiCad, a free EDA CAD application.
 *
 * Copyright The KiCad Developers, see AUTHORS.txt for contributors.
 *
 * This program is free software: you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the
 * Free Software Foundation, either version 3 of the License, or (at your
 * option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#include "multi_board_sch_pad_scan.h"

#include <connection_graph.h>
#include <eeschema_helpers.h>
#include <pin_type.h>
#include <sch_connection.h>
#include <sch_pin.h>
#include <sch_screen.h>
#include <sch_sheet_path.h>
#include <sch_symbol.h>
#include <schematic.h>

#include <wx/log.h>


namespace
{

/**
 * Skip auto-generated KiCad net names ("Net-(R1-Pad2)", "unconnected-…").
 * These provide no value as cross-board net labels — the placeholder
 * `J1.1` style produced upstream is more readable.
 */
bool isAutoGeneratedNetName( const wxString& aName )
{
    if( aName.IsEmpty() )
        return true;

    if( aName.StartsWith( wxT( "Net-(" ) ) )
        return true;

    if( aName.StartsWith( wxT( "unconnected-" ) ) )
        return true;

    return false;
}

}   // anonymous namespace


std::map<wxString, std::vector<MULTI_BOARD_PAD_INFO>>
MultiBoardLoadConnectorPadsFromSch( const wxFileName& aSchFile )
{
    std::map<wxString, std::vector<MULTI_BOARD_PAD_INFO>> result;

    if( !aSchFile.FileExists() )
        return result;

    // EESCHEMA_HELPERS::LoadSchematic with aCalculateConnectivity=true
    // runs the same SCH load + connection-graph rebuild that eeschema
    // does interactively, so SCH_PIN::Connection(sheet)->Name() returns
    // properly resolved net names. We don't make this load the active
    // schematic (aSetActive=false) — refreshing the MBS shouldn't yank
    // the user's editing context.
    SCHEMATIC* schematic = nullptr;

    try
    {
        schematic = EESCHEMA_HELPERS::LoadSchematic( aSchFile.GetFullPath(),
                                                      /*aSetActive=*/false,
                                                      /*aForceDefaultProject=*/false,
                                                      /*aProject=*/nullptr,
                                                      /*aCalculateConnectivity=*/true );
    }
    catch( ... )
    {
        wxLogTrace( wxT( "MBS" ),
                    wxT( "MultiBoardLoadConnectorPadsFromSch: LoadSchematic threw on %s" ),
                    aSchFile.GetFullPath() );
        return result;
    }

    if( !schematic )
        return result;

    SCH_SHEET_LIST sheets = schematic->Hierarchy();

    for( const SCH_SHEET_PATH& sheet : sheets )
    {
        SCH_SCREEN* screen = sheet.LastScreen();

        if( !screen )
            continue;

        for( SCH_ITEM* item : screen->Items().OfType( SCH_SYMBOL_T ) )
        {
            SCH_SYMBOL* symbol = static_cast<SCH_SYMBOL*>( item );
            wxString    ref    = symbol->GetRef( &sheet, /*aIncludeUnit=*/false );

            if( !MultiBoardIsConnectorRef( ref ) )
                continue;

            // First-instance-wins across sheets (same dedup as the regex
            // scanner). A connector reference appearing on multiple sheet
            // paths is rare but possible.
            if( result.count( ref ) )
                continue;

            std::vector<MULTI_BOARD_PAD_INFO>& pads = result[ref];

            for( SCH_PIN* pin : symbol->GetPins( &sheet ) )
            {
                if( !pin )
                    continue;

                MULTI_BOARD_PAD_INFO info;
                info.padNumber      = pin->GetShownNumber();
                info.electricalType = pin->GetType();

                if( SCH_CONNECTION* conn = pin->Connection( &sheet ) )
                {
                    wxString netName = conn->Name();

                    if( !isAutoGeneratedNetName( netName ) )
                        info.netName = netName;
                }

                // Same per-ref dedup as scanConnectorPads — collapse pins
                // that share a number (rare but valid for tied power pins).
                bool duplicate = false;

                for( const MULTI_BOARD_PAD_INFO& existing : pads )
                {
                    if( existing.padNumber == info.padNumber )
                    {
                        duplicate = true;
                        break;
                    }
                }

                if( !duplicate )
                    pads.push_back( info );
            }
        }
    }

    return result;
}
