/*
 * This program source code file is part of KiCad, a free EDA CAD application.
 *
 * Copyright The KiCad Developers, see AUTHORS.txt for contributors.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, you may find one here:
 * http://www.gnu.org/licenses/old-licenses/gpl-2.0.html
 */

#ifndef MULTI_BOARD_NET_EXTRACTOR_H
#define MULTI_BOARD_NET_EXTRACTOR_H

#include <project/project_file.h>

#include <vector>

class SCH_SCREEN;


/**
 * Walk a multi-board schematic's topology and extract the set of nets that
 * connect pins on two or more SCH_MODULE_BLOCK items.
 *
 * Uses a lightweight wire-based union-find rather than CONNECTION_GRAPH:
 * two SCH_MODULE_PIN positions end up in the same net if they are
 * reachable by SCH_LINE wires. Net name is taken from an attached label
 * on the shared set (SCH_LABEL / SCH_GLOBAL_LABEL / SCH_HIER_LABEL) when
 * present, else autogenerated as "Net-<uuid8>".
 *
 * `aMultiBoard` is used to map each module block's sub_project_path back
 * to a sub-project uuid — blocks whose path does not match a registered
 * sub-project are still emitted (with a nil uuid) so the caller can
 * diagnose.
 *
 * Only single-screen (flat) MBS schematics are considered. Hierarchical
 * sub-sheets inside the MBS are not traversed.
 */
std::vector<MB_CROSS_BOARD_NET> ExtractCrossBoardNets( SCH_SCREEN& aMbsScreen,
                                                    const PROJECT_FILE& aMultiBoard );

#endif // MULTI_BOARD_NET_EXTRACTOR_H
